# Generated by Django 5.1.1 on 2024-10-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_inventaire', models.IntegerField(default=2024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_article', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.designation')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.famille')),
            ],
        ),
        migrations.CreateModel(
            name='DetailInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.inventaire')),
                ('status_article', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cnc_app.statusarticle')),
            ],
        ),
        migrations.CreateModel(
            name='DetailEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_entree', models.IntegerField()),
                ('code_article', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.article')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.emplacement')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.origine')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.statusarticle')),
            ],
        ),
    ]
