# Generated by Django 5.1.2 on 2024-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailentree',
            name='marque',
            field=models.CharField(default='non-spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='detailentree',
            name='modele',
            field=models.CharField(default='non-spécifié', max_length=100),
        ),
    ]
