# Generated by Django 5.1.2 on 2024-10-23 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0002_detailentree_marque_detailentree_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailentree',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailinventaire',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
