# Generated by Django 5.1.2 on 2024-10-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0004_designation_famille_designation_marque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailentree',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='detailentree',
            name='modele',
        ),
    ]
